name: "Validate"

on:
  workflow_dispatch:
  push:
  pull_request:
  schedule:
    - cron:  "0 0 * * *"

jobs:
  hassfest: # https://developers.home-assistant.io/blog/2020/04/16/hassfest
    name: "Hassfest Validation"
    runs-on: "ubuntu-latest"
    steps:
        - name: "Checkout the repository"
          uses: "actions/checkout@v4.1.5"
          with:
            token: ${{ secrets.WORKFLOW_PAT || github.token }}
            ref: ${{ github.head_ref }}

        - name: "Run hassfest validation"
          uses: "home-assistant/actions/hassfest@master"

  hacs: # https://github.com/hacs/action
    name: "HACS Validation"
    runs-on: "ubuntu-latest"
    steps:
        - name: "Checkout the repository"
          uses: "actions/checkout@v4.1.5"
          with:
            token: ${{ secrets.WORKFLOW_PAT || github.token }}
            ref: ${{ github.head_ref }}

        - name: "Run HACS validation"
          uses: "hacs/action@main"
          with:
            category: "integration"
            # Remove this 'ignore' key when you have added brand images for your integration to https://github.com/home-assistant/brands
            #ignore: "brands"
